[project]
name = "pokefusion"
version = "2.0.0"
requires-python = "~=3.14.0"
dependencies = [
    "aiohttp>=3.14.3",
    "discord-py>=2.7.1",
    "fuzzywuzzy>=0.18.0",
    "levenshtein>=0.27.3",
    "peewee>=4.2.6",
    "peewee-migrate>=1.15.0",
    "pillow>=12.3.0",
    "scikit-image>=0.26.0",
    "tqdm>=4.69.0",
    "typer>=0.27.0",
    "tzdata>=2026.3",
    "unidecode>=1.4.0",
]
