[project]
name = "pokefusion"
version = "2.0.0"
requires-python = "~=3.14.0"
dependencies = [
    "aiohttp>=3.14.3",
    "discord-py>=2.7.1",
    "fuzzywuzzy>=0.18.0",
    "levenshtein>=0.27.4",
    "peewee>=4.4.0",
    "peewee-migrate>=2.3.0",
    "pillow>=12.3.0",
    "scikit-image>=0.26.0",
    "tqdm>=4.70.0",
    "typer>=0.27.2",
    "tzdata>=2026.3",
    "unidecode>=1.4.0",
]
