from pathlib import Path

from pokefusion.assetpaths import AssetPaths
from pokefusion.configmanager import ConfigManager

CACHE_DIR = Path("cache")
PACKS_DIR = Path("packs")
STAGING_DIR = Path("staging")

AUTOGEN_REPOSITORY_DIR = CACHE_DIR / "infinitefusion-e18"
AUTOGEN_SPRITESHEETS_RELATIVE_DIR = Path("Graphics", "Battlers", "spritesheets_autogen")
AUTOGEN_SPRITESHEETS_DIR = AUTOGEN_REPOSITORY_DIR / AUTOGEN_SPRITESHEETS_RELATIVE_DIR

STAGING_FUSIONS_DIR = STAGING_DIR / "fusions"
STAGING_AUTOGEN_DIR = STAGING_FUSIONS_DIR / "autogen"
STAGING_CUSTOM_DIR = STAGING_FUSIONS_DIR / "custom"
STAGING_EGGS_DIR = STAGING_DIR / "eggs"
STAGING_DEFAULT_EGG_PATH = STAGING_EGGS_DIR / AssetPaths.DEFAULT_EGG_PATH.name

STAGING_CUSTOM_FUSIONS_PATH = STAGING_DIR / ConfigManager.CUSTOM_FUSIONS_FILE
STAGING_AUTOGEN_DIFF_ADDED_PATH = STAGING_DIR / ConfigManager.AUTOGEN_DIFF_ADDED_FILE
STAGING_AUTOGEN_DIFF_REMOVED_PATH = STAGING_DIR / "autogen_diff_removed.json"
STAGING_CUSTOM_DIFF_ADDED_PATH = STAGING_DIR / ConfigManager.CUSTOM_DIFF_ADDED_FILE
STAGING_CUSTOM_DIFF_REMOVED_PATH = STAGING_DIR / "custom_diff_removed.json"
STAGING_EGGS_DIFF_ADDED_PATH = STAGING_DIR / "eggs_diff_added.json"
STAGING_EGGS_DIFF_REMOVED_PATH = STAGING_DIR / "eggs_diff_removed.json"

CUSTOM_FUSIONS_CONFIG_PATH = ConfigManager.CONFIG_DIR / STAGING_CUSTOM_FUSIONS_PATH.name
AUTOGEN_DIFF_ADDED_CONFIG_PATH = ConfigManager.CONFIG_DIR / STAGING_AUTOGEN_DIFF_ADDED_PATH.name
CUSTOM_DIFF_ADDED_CONFIG_PATH = ConfigManager.CONFIG_DIR / STAGING_CUSTOM_DIFF_ADDED_PATH.name

STAGING_METADATA_PATHS = (
    STAGING_CUSTOM_FUSIONS_PATH,
    STAGING_AUTOGEN_DIFF_ADDED_PATH,
    STAGING_AUTOGEN_DIFF_REMOVED_PATH,
    STAGING_CUSTOM_DIFF_ADDED_PATH,
    STAGING_CUSTOM_DIFF_REMOVED_PATH,
    STAGING_EGGS_DIFF_ADDED_PATH,
    STAGING_EGGS_DIFF_REMOVED_PATH,
)

APPLIED_METADATA_PATHS = {
    STAGING_CUSTOM_FUSIONS_PATH: CUSTOM_FUSIONS_CONFIG_PATH,
    STAGING_AUTOGEN_DIFF_ADDED_PATH: AUTOGEN_DIFF_ADDED_CONFIG_PATH,
    STAGING_CUSTOM_DIFF_ADDED_PATH: CUSTOM_DIFF_ADDED_CONFIG_PATH,
}
